apiVersion: v1
kind: Service
metadata:
  name: ycity-app-service
  labels:
    app: ycity-app
spec:
  selector:
    app: ycity-app
  ports:
  - protocol: TCP
    port: 80         # Service port
    targetPort: 3000  # Application port from Deployment
  type: LoadBalancer
